#!/bin/bash


if [ -d /Library/Extensions ]; then
    touch /Library/Extensions
    if [ -d /Library/Extensions/MovaviSoundGrabber.kext ]; then
        kextload /Library/Extensions/MovaviSoundGrabber.kext
        exit 0
    fi
fi

if [ -d /Library/Extensions ]; then
    touch /System/Library/Extensions
    if [ -d /System/Library/Extensions/MovaviSoundGrabber.kext ]; then
        kextload /System/Library/Extensions/MovaviSoundGrabber.kext
    fi
fi
